// <auto-generated />
using ConsoleApp.Domain.Uow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsoleApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp.Domain.Entities.DiscordGuild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("DiscordGuilds");
                });

            modelBuilder.Entity("ConsoleApp.Domain.Entities.DiscordGuild", b =>
                {
                    b.OwnsOne("ConsoleApp.Domain.Entities.OwnedTypes.ClanSettings", "ClanSettings", b1 =>
                        {
                            b1.Property<decimal>("OwnerId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("MaxMembers")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(5);

                            b1.HasKey("OwnerId");

                            b1.ToTable("DiscordGuilds");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.Navigation("ClanSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
